// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_JPZWyRfNlvg3vVeB_d8FGV_n7xsffUk',
    appId: '1:843827003458:web:5b9958deaf9d3796832ddb',
    messagingSenderId: '843827003458',
    projectId: 'devault-a4416',
    authDomain: 'devault-a4416.firebaseapp.com',
    storageBucket: 'devault-a4416.firebasestorage.app',
    measurementId: 'G-GV2BZ2BZCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMTC5lL-70MtqIWyeEJrMVqtnHDbgY1Dk',
    appId: '1:843827003458:android:6dcdfdf61f9596b6832ddb',
    messagingSenderId: '843827003458',
    projectId: 'devault-a4416',
    storageBucket: 'devault-a4416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfu0x2eVcToXdOC5oZjejvDjRNhA1HKUw',
    appId: '1:843827003458:ios:76120431eafca3b6832ddb',
    messagingSenderId: '843827003458',
    projectId: 'devault-a4416',
    storageBucket: 'devault-a4416.firebasestorage.app',
    androidClientId: '843827003458-oo22rchhsm42p4v3h1r36p7026iraod0.apps.googleusercontent.com',
    iosClientId: '843827003458-8j58f4q5737lu70ldm45qhdhgvho0621.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyypc4MyqBBneptEWpF17u3s7cu8X4wIY',
    appId: '1:823307041176:ios:3be076689b6866ea0653ed',
    messagingSenderId: '823307041176',
    projectId: 'codingwitht-c6d0f',
    storageBucket: 'codingwitht-c6d0f.appspot.com',
    androidClientId: '823307041176-qfcmju8p2mbqre4rl5kufhr7dhs9hs33.apps.googleusercontent.com',
    iosClientId: '823307041176-7pen3ehk09mbnp7ukg6lm4a9sgr80pjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp.RunnerTests',
  );
}